// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using dotnet7_new_features.Queries;

#nullable disable

namespace dotnet7newfeatures.Migrations
{
    [DbContext(typeof(QueryEnhancementsContext))]
    partial class QueryEnhancementsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("VehicleSequence");

            modelBuilder.Entity("dotnet7_new_features.EfCore.InheritanceStrategies.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValueSql("nextval('\"VehicleSequence\"')");

                    NpgsqlPropertyBuilderExtensions.UseSequence(b.Property<int>("Id"));

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("dotnet7_new_features.Queries.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("dotnet7_new_features.EfCore.InheritanceStrategies.Bus", b =>
                {
                    b.HasBaseType("dotnet7_new_features.EfCore.InheritanceStrategies.Vehicle");

                    b.Property<int>("SeatCount")
                        .HasColumnType("integer");

                    b.ToTable("Buses");
                });

            modelBuilder.Entity("dotnet7_new_features.EfCore.InheritanceStrategies.Car", b =>
                {
                    b.HasBaseType("dotnet7_new_features.EfCore.InheritanceStrategies.Vehicle");

                    b.Property<int>("DoorCount")
                        .HasColumnType("integer");

                    b.Property<string>("Segment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable("Cars");
                });
#pragma warning restore 612, 618
        }
    }
}
