# this is an replacement for postman
# Get weather forecast

GET https://localhost:7120/WeatherForecast

###

# GetWithParsable

GET https://localhost:7120/WeatherForecast/1-3

### 

# IResultSupported

GET https://localhost:7120/WeatherForecast/IResultSupported
